language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install pdoc
script:
  - pytest
  # generate the docs
  - mkdir docs
  - cd docs
  - pdoc --html -o . --force pvinspect
  - mv pvinspect/*.html .
  - rm -rf pvinspect/
  - cd ../

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: docs/