language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install pdoc3
script:
  - pytest
  - pdoc3 --html pvinspect

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    tags: true
  local_dir: html/pvinspect/